HKStat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from HotKeyStat.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'', include('HotKeyStat.urls'), name='HotKeyStat'),
]

HotKeyStat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='HotKeyStat-index'),
    url(r'ProgressOverview/$', views.progress, name='hkstat-progress'),
    url(r"^ProgressOverview/block/$", views.progress_block, name='hkstat-progress-block'),
    url(r"^ProgressOverview/block/(?P<block_id>\d+)/$", views.progress_topic, name='hkstat-progress-topic'),
    url(r'^ModuleDetails/$', views.module_details, name='hkstat-module-details'),
    url(r"^ModuleDetails/block/(?P<block_id>\d+)/$", views.block_details, name='hkstat-block-details'),
    url(r"^result/$", views.result_save, name='result-save'),
    url(r'^ProgressOverview/report/$', views.progress_report, name='hkstat-progress-report'),
    url(r'^Champions/$', views.champions, name='hkstat-champions'),
]

HotKeyStat/forms.py
# -*- coding:utf-8  -*-
u'''
Формы приложения HotKeyStat
'''
from django import forms
# from django.core.exceptions import ValidationError
# from django.contrib.auth.decorators import permission_required
# from HotKeyStat.models import (Learner, Result, Block)


# from django_tools.middlewares import ThreadLocal

class LearnerFilterForm(forms.Form):
    u'''
    Форма количество проголосовавших на контрольное время по избирательному участку
    '''
    date_from = forms.DateField(
        label=u'Date From', 
        widget=forms.DateInput(),
        required=False,
    )
    date_by = forms.DateField(label=u'Date To', required=False)
    

HotKeyStat/views.py
# -*- coding: utf-8 -*-

import base64
from copy import deepcopy
from datetime import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseForbidden
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.db.models import Max, Count, Sum, Avg

# import xlrd
import xlwt
import math
# from xlutils.copy import copy

from HotKeyStat.models import (
    Learner, Block, TypeResults, Result, Organizations, Manager
    )
from .forms import LearnerFilterForm

# Create your views here.

# стили форматирования для вывода в отчет

style_none = xlwt.easyxf('''font: name Calibri, height 200, color_index black;
    border: left 0, right 0, top 0, bottom 0;
    alignment: horz CENTER, vert CENTER;
    align: wrap 1
''')
style_right = deepcopy(style_none)
style_right.borders.right = 1
style_right_left_text = deepcopy(style_right)
style_right_left_text.alignment.horz = 1
style_left = deepcopy(style_none)
style_left.borders.left = 1

# нижняя граница текст жирно
style_bold_bottom_gray = xlwt.easyxf('''font: name Calibri, height 200, color_index black, bold on;
    border: left 0, right 0, top 0, bottom 1;
    alignment: horz CENTER, vert CENTER;
    pattern: pattern 1, pattern_fore_colour 67;
    align: wrap 1;
''')
style_bold_bottom_green = deepcopy(style_bold_bottom_gray)
style_bold_bottom_green.pattern.pattern_fore_colour = 42
style_bold_bottom_pink = deepcopy(style_bold_bottom_gray)
style_bold_bottom_pink.pattern.pattern_fore_colour = 26
style_bottom_gray = deepcopy(style_bold_bottom_gray)
style_bottom_gray.font.bold = 0
style_bottom_gray.alignment.horz = 1
style_bottom_gray.alignment.wrap = 0
style_bottom_right_gray = deepcopy(style_bottom_gray)
style_bottom_right_gray.borders.right = 1

# правая и нижняя граница текст жирно
style_bold_bottom_right_pink = deepcopy(style_bold_bottom_gray)
style_bold_bottom_right_pink.borders.right = 1
style_bold_bottom_right_pink.pattern.pattern_fore_colour = 26
style_bold_bottom_right_green = deepcopy(style_bold_bottom_gray)
style_bold_bottom_right_green.borders.right = 1
style_bold_bottom_right_green.pattern.pattern_fore_colour = 42

# левая и нижняя граница текст жирно
style_bold_bottom_left_pink = deepcopy(style_bold_bottom_gray)
style_bold_bottom_left_pink.borders.left = 1
style_bold_bottom_left_pink.pattern.pattern_fore_colour = 26
style_bold_bottom_left_green = deepcopy(style_bold_bottom_gray)
style_bold_bottom_left_green.borders.left = 1
style_bold_bottom_left_green.pattern.pattern_fore_colour = 42

# Левая, правая и нижняя граница - текст жирно
style_bold_left_right_pink = deepcopy(style_bold_bottom_left_pink)
style_bold_left_right_pink.borders.right = 1
style_bold_left_right_green = deepcopy(style_bold_bottom_left_green)
style_bold_left_right_green.borders.left = 1

# Нижняя граница, нежирный текст
style_bottom_green = deepcopy(style_bold_bottom_green)
style_bottom_green.font.bold = 0
style_bottom_pink = deepcopy(style_bold_bottom_pink)
style_bottom_pink.font.bold = 0

# Нижняя и правая граница, нежирный текст
style_bottom_right_green = deepcopy(style_bold_bottom_green)
style_bottom_right_green.borders.right = 1
style_bottom_right_green.font.bold = 0
style_bottom_right_pink = deepcopy(style_bold_bottom_pink)
style_bottom_right_pink.borders.right = 1
style_bottom_right_pink.font.bold = 0

# Нижняя и левая граница, нежирный текст
style_bottom_left_green = deepcopy(style_bold_bottom_green)
style_bottom_left_green.borders.left = 1
style_bottom_left_green.font.bold = 0
style_bottom_left_pink = deepcopy(style_bold_bottom_pink)
style_bottom_left_pink.borders.left = 1
style_bottom_left_pink.font.bold = 0

# Нижняя, правая и левая граница, нежирный текст
style_left_right_green = deepcopy(style_bold_left_right_green)
style_left_right_green.font.bold = 0
style_left_right_pink = deepcopy(style_bold_left_right_pink)
style_left_right_pink.font.bold = 0


def base64_url_decode(inp):
    padding_factor = (4 - len(inp) % 4) % 4
    inp += "="*padding_factor 
    # s = base64.b64decode(b64_string)
    return base64.b64decode(inp.translate(dict(zip(map(ord, u'-_'), u'+/'))))


def get_time_str(excercise_time):
    u"""
    Возвращает время ученика в формате "Nmin Ms"
    """
    excercise_time_str = "0"
    if excercise_time > 60:
        excercise_time_sec = excercise_time%60
        excercise_time_min = excercise_time/60
        excercise_time_str = str(int(excercise_time_min)) + "min " + str(int(excercise_time_sec)) + "sес"
    elif excercise_time > 0:
        excercise_time_str = str(int(excercise_time)) + "s"
    
    return excercise_time_str


# @permission_required('HotKeyStat.view_statistic')
def index(request):
    u'''
    Страница выбора типа отчета
    '''
    if not request.user.is_authenticated:
        return redirect('login')

    user = request.user
    manager = user.manager
    # Проверяем права доступа текущего менеджера.
    if manager is None:
        return HttpResponseForbidden(u"You don't have enough rights. Please contact support")
    org = manager.org
    return render(request, 'index.html', {
        'org': org,
    })



# @permission_required('HotKeyStat.view_statistic')
def progress(request):
    u'''
    отчет Прогресс
    '''
    user = request.user
    manager = user.manager
    # Проверяем права доступа текущего менеджера.
    if manager is None:
        return HttpResponseForbidden(u"You don't have enough rights. Please contact support")
    
    # Списки учеников, результаты которых доступны текущему проверяющему:
    learners = manager.get_learner_list()
    form = LearnerFilterForm(request.GET)
    if form.is_valid():
        if form.cleaned_data["date_from"]:
            learners = learners.filter(date_reg__gte=form.cleaned_data["date_from"])
        if form.cleaned_data[u"date_by"]:
            learners = learners.filter(date_reg__lte=form.cleaned_data[u"date_by"])

    order = u'surname'
    if request.GET.get('order', None) :
        order = request.GET['order']
    # Списки учеников, результаты которых доступны текущему проверяющему:
    if order == u'date_reg' or order == u'-date_reg':
        learners = learners.order_by(order, u'surname')
    else:
        learners = learners.order_by(order, u'date_reg')
    
        
    # Списки родительских блоков
    # parent_blocks = Block.get_parent_block()

    academy_type = TypeResults.objects.get(code=0)
    game_type = TypeResults.objects.get(code=1)
    mixgame_type = TypeResults.objects.get(code=2)

    # Список редультатов всех учеников
    all_results = []
    # список заголовков таблицы
    headers = [u'Name', u'E-mail', u'Start Date', u'Overall Progress', u'Graph', u'Excel Excercise']
    # проценты ученика по академии, игре, mixGame и общий процент
    academy_percent = 0
    game_percent = 0
    mixgame_percent = 0
    all_percent = 0
    # общий максимальный процент
    all_max_percent = 0

    for learner in learners:
        # список результатов каждого ученика
        learner_results = []
        learner_results.append(learner)
        academy_percent = learner.get_result_type(academy_type)
        game_percent = learner.get_result_type(game_type)
        mixgame_percent = learner.get_result_type(mixgame_type)
        time = get_time_str(learner.get_learner_avgtime(game_type))
        all_percent = academy_percent + game_percent + mixgame_percent

        # Максимальное кол-во ключей по академии равно мак кол-ву ключей по игре
        maxkey_academy = Block.get_max_academy() or 0
        # Максимальное кол-во ключей по mixgame
        maxkey_mixgame = Block.get_max_MixGame() or 0
        if maxkey_academy and maxkey_academy > 0:
            academy_percent = 100.00*(academy_percent/maxkey_academy)
            game_percent = 100.00*(game_percent/maxkey_academy)
        if maxkey_mixgame and maxkey_mixgame > 0:
            mixgame_percent = 100.00*(mixgame_percent/maxkey_mixgame)  
        # Общий процент по академии, игре и mixgame
        all_max_percent = 2* maxkey_academy + maxkey_mixgame
        if all_max_percent and all_max_percent > 0:
            all_percent = 100.00*(all_percent/all_max_percent)

        # Excel Excercise
        excercise_percent = learner.get_result_excercise()
        excercise_time = get_time_str(learner.get_time_excercise())
        # excercise_time = learner.get_time_excercise()


        learner_results.append( 
            {
                "academy": academy_percent, 
                "game": game_percent, 
                "time": time,
                "all_percent": all_percent, 
                "excercise_percent": excercise_percent,
                "excercise_time": excercise_time,
            }
        )
        # learner_results.append(results)
        all_results.append(learner_results)
    
    return render(request, 'progress.html', {
        'all_results': all_results,
        'headers': headers,
        'order': order,
        'form': form,
    })


# @permission_required('HotKeyStat.view_statistic')
def progress_block(request):
    u'''
    отчет Прогресс по блокам
    '''
    user = request.user
    manager = user.manager
    # Проверяем права доступа текущего менеджера.
    if manager is None:
        return HttpResponseForbidden(u"You don't have enough rights. Please contact support")

    date_from = None
    date_from_s = None
    date_by = None
    date_by_s = None
    order = u'surname'
    if request.GET.get('order', None) :
        order = request.GET['order']
    if request.GET.get('date_from', None) :
        date_from = request.GET['date_from']

HotKeyStat/templates/block_detail.html
{% extends "report.html" %}
{% load static %}

{% block breadcrumbs %}
    <li><a href="{% url 'HotKeyStat-index' %}">Home</a> </li>
    <li><a href="{% url 'hkstat-module-details' %}">Module Details (main)</a> </li>
    <li class='active'>{{ parent_block }}</li>
{% endblock %}

{% block page_header %}
<div class="row" >
    <div class="col-md-offset-3 col-md-5">
        <h2 align="center">
            <span class="glyphicon glyphicon-signal" aria-hidden="true"></span> &nbsp;
            Module Details<br>
            <small>{{ parent_block }}</small>
        </h2>
    </div>
    <div class="col-md-2" style="margin-top:3mm;">
            <a href="{% url 'hkstat-progress-report' %}{% if form.date_from.value %}?date_from={{form.date_from.value}}{% endif %}{% if form.date_from.value and form.date_by.value %}&date_by={{form.date_by.value}}{% elif form.date_by.value %}?date_by={{form.date_by.value}}{% endif %}" 
            class="btn btn-warning btn-block ">
            Export to Excel
            </a>
    </div>
</div>
{% endblock %}

{% block page_content %}

{% if errors %}
    <div class="alert alert-danger" role="alert">
        {% for er in errors %}
            {{ er }}<br/>
        {% endfor %}
        </p>
    </div>
{% endif %}
{% if messages %}
<div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    {% for message in messages %}
        {{ message }}<br>
    {% endfor %}
</div>
{% endif %}

{% csrf_token %}
<table class="table table-striped table-condensed">
    <tr>
        {% for header in headers %}
        <td width="25%"
        {% if forloop.counter0 > 0 %}
            align="center" 
        {% endif %}
        {% if forloop.counter0 == 2 %}
            colspan="2"
        {% endif %}
            >
            <b style="color: #167249">
                {{ header }}
            </b>
        </td>
        {% endfor %}
    </tr>
    <tr></tr>
    <tr>
        <td></td><td></td>
        {% if parent_block.number_block != '500' %}
            <td align="right"><span class="glyphicon glyphicon-education" aria-hidden="true" style="padding-right:15px; color: #167249"></span> &nbsp;</td>
            <td align="left"><img src="{% static "/media/game.png" %}"  alt="Game" style="padding-left:15px"></td>
        {% elif parent_block.number_block == '500' %}
            <td align="center" colspan="2"><img src="{% static "/media/game.png" %}"  alt="Game"></td>
        {% endif %}
        <td></td>
    </tr>
    {% for learner, results in all_results %}
    <tr>
        <td align="left" style="color: #167249">
            <b> {{ learner }} </b>
        </td>
        <td align="center">
            {{results.time}}
        </td>
        {% if parent_block.number_block != '500' %}
            <td align="right" title="Academy" style="color:#eb6f1f">
                {{results.academy|floatformat:2}}% &nbsp;
            </td>
            <td align="left" title="Game" style="color:#167249">
        {% endif %}
        {% if parent_block.number_block == '500' %}  
            <td align="center" title="Game" colspan="2">
        {% endif %}
            {{results.game|floatformat:2}}%
        </td>

        <td align="center" width="20%">
            <div class="progress">
                <div 
                {% if results.result_all >= 50 %}
                    class="progress-bar progress-bar-success" 
                {% else %}
                    class="progress-bar progress-bar-warning"
                {% endif %}
                role="progressbar" 
                    aria-valuenow={{results.result_all}}
                    aria-valuemin="0"
                    aria-valuemax="100" 
                    style="min-width: 3em; width: {{results.result_all|floatformat:2}}%">
                    {{results.result_all|floatformat:2}}%
                </div>
            </div>
            
        </td>
        
    </tr>
    {% endfor %}
</table>

{% endblock %}

HotKeyStat/templates/champions.html
{% extends "report.html" %}
{% load static %}

{% if state == 'manager' %}
{% block breadcrumbs %}
    <li><a href="{% url 'HotKeyStat-index' %}">Home</a> </li>
    <li class='active'>Hot Key Champions</li>
{% endblock %}
{% endif %}

{% block page_header %}
    <h3 align="center">
        <span><img src="{% static "/media/key_green.png" %}" ></span> &nbsp;
        Hot Key Champions of {{ organization }}
    </h3>
{% endblock %}

{% block page_content %}

{% if errors %}
    <div class="alert alert-danger" role="alert">
        {% for er in errors %}
            {{ er }}<br/>
        {% endfor %}
        </p>
    </div>
{% endif %}
{% if messages %}
<div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    {% for message in messages %}
        {{ message }}<br>
    {% endfor %}
</div>
{% endif %}

{% csrf_token %}

{% if places %}

<table width="40%" align="center" style="color: #167249">
    <tr>
        <td align="center" valign="bottom"><img src="{% static "/media/chemp2.png" %}"  alt="Game"></td>
        <td align="center" valign="bottom"><img src="{% static "/media/chemp1.png" %}"  alt="Game"></td>
        <td align="center" valign="bottom"><img src="{% static "/media/chemp3.png" %}"  alt="Game"></td>
    </tr>
    <tr>
        {% for place in places%}
            <td align="center">
                {{ place.learner.name }} {{ place.learner.surname }} <br>
                {{place.time}}
            </td>
        {% endfor %}
    </tr>
</table>
{% endif %}
<br>
{% if all_results %}
<table class="table table-striped table-condensed">
    <tr>
        {% for header in headers %}
        <td  style="color:#167249" align="center"
            header
            {% if header == 'Excel Excercise' %}
                colspan="2"
            {% endif %}
        > <b>
            {% if header == "Ranking" %}
                {% if order == "rank" %}
                    <a href="{% url 'hkstat-champions' %}?order=-rank">
                {% else %}
                    <a href="{% url 'hkstat-champions' %}?order=rank">
                {% endif %}
                    {{ header }}
                    <span 
                    {% if order == "-rank" %}
                        class="glyphicon glyphicon-triangle-top"
                    {% else %}
                        class="glyphicon glyphicon-triangle-bottom" 
                    {% endif %}
                    aria-hidden="true" ></span>
                </a>
            {% elif header == "Date" %}
                {% if order == "date_reg" %}
                    <a href="{% url 'hkstat-champions' %}?order=-date_reg">
                {% else %}
                    <a href="{% url 'hkstat-champions' %}?order=date_reg">
                {% endif %}
                    {{ header }}
                    <span 
                    {% if order == "-date_reg" %}
                        class="glyphicon glyphicon-triangle-top"
                    {% else %}
                        class="glyphicon glyphicon-triangle-bottom" 
                    {% endif %}
                    aria-hidden="true" ></span>
                </a>
            {% elif header == "Last Name" %}
                {% if order == "surname" %}
                    <a href="{% url 'hkstat-champions' %}?order=-surname">
                {% else %}
                    <a href="{% url 'hkstat-champions' %}?order=surname">
                {% endif %}
                    {{ header }}
                    <span 
                    {% if order == "-surname" %}
                        class="glyphicon glyphicon-triangle-top"
                    {% else %}
                        class="glyphicon glyphicon-triangle-bottom" 
                    {% endif %}
                    aria-hidden="true" ></span>
                </a>
            {% else %}
                {{ header }} </b>
            {% endif %}   
        </td>
        {% endfor %}
    </tr>
    <tr></tr>
    <tr>
        <td></td><td></td><td></td><td></td><td></td>
        <td align="right" style="padding-right:20px"><img src="{% static "/media/game.png" %}"  alt="Game"></td>
        <td align="left" style="padding-left:20px"><span class="glyphicon glyphicon-time" aria-hidden="true" style="color: #167249"></span> &nbsp;</td>
    </tr>
    {% for learner, result in all_results %}
    <tr align="center">
        <td> {% if learner.rank < 100000 %}
                {{learner.rank}} 
            {% else %} --
            {% endif %}
        </td>
        <td> {{learner.date_reg|date:"m/d/Y"}} </td>
        <td> {{learner.name}} </td>
        <td> {{learner.surname}} </td>
        
        <td>{{ result.key_count }}</td> 
        <td align="right" style="padding-left:20px" title="Excel Excercise Percent">
            {{result.excercise_percent|floatformat:2}}% &nbsp;
        </td>
        <td align="left" style="padding-left:20px" title="Excel Excercise Time">
            {{result.excercise_time}}
        </td>

    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

HotKeyStat/templates/progress.html
{% extends "report.html" %}
{% load static %}

{% block breadcrumbs %}
    <li><a href="{% url 'HotKeyStat-index' %}">Home</a> </li>
    <li class='active'>Learner Progress (main)</li>
{% endblock %}


{% block page_header %}
<div class="row" >
    <div class="col-md-offset-3 col-md-5">
        <h2 align="center">
            <span class="glyphicon glyphicon-education" aria-hidden="true"></span> &nbsp;
            Learner Progress <small> main </small>
        </h2>
    </div>
        <div class="col-md-2" style="margin-top:3mm;">
            <a href="{% url 'hkstat-progress-report' %}{% if form.date_from.value %}?date_from={{form.date_from.value}}{% endif %}{% if form.date_from.value and form.date_by.value %}&date_by={{form.date_by.value}}{% elif form.date_by.value %}?date_by={{form.date_by.value}}{% endif %}" 
            class="btn btn-warning btn-block ">
            Export to Excel
            </a>
        </div>
</div>
{% endblock %}

{% block page_content %}
{% if errors %}
    <div class="alert alert-danger" role="alert">
        {% for er in errors %}
            {{ er }}<br/>
        {% endfor %}
        </p>
    </div>
{% endif %}
{% if messages %}
<div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    {% for message in messages %}
        {{ message }}<br>
    {% endfor %}
</div>
{% endif %}

{% csrf_token %}

<form class="form-inline" action="." method="GET">
    <div class="form-group">
        <label for="id_date_from" style="color:#167249">DateFrom</label>
        <input type="date" class="form-control" name="date_from" id="date_from" 
        {% if form.date_from %} value= {{form.date_from.value}} {% endif %}>
    </div>&nbsp;
    <div class="form-group">
        <label for="date_by" style="color:#167249">DateTo</label>
        <input type="date" class="form-control" id="date_by" name="date_by" 
        {% if form.date_by %}value={{form.date_by.value}} {% endif %}>
    </div>
    <input type="submit"  class='btn btn-warning' value="Filter">
</form>
<br>
<table class="table table-striped table-condensed">
    <tr>
        <td  width="10%">
            <b>
                {% if order == "surname" %}
                    <a href="{% url 'hkstat-progress' %}?order=-surname{% if form.date_from.value %}&date_from={{form.date_from.value}}{% endif %}{% if form.date_by.value %}&date_by={{form.date_by.value}}{% endif %}">
                {% else %}
                    <a href="{% url 'hkstat-progress' %}?order=surname{% if form.date_from.value %}&date_from={{form.date_from.value}}{% endif %}{% if form.date_by.value %}&date_by={{form.date_by.value}}{% endif %}">
                {% endif %}
                    Last Name
                <span 
                {% if order == "-surname" %}
                    class="glyphicon glyphicon-triangle-top"
                {% else %}
                    class="glyphicon glyphicon-triangle-bottom" 
                {% endif %}
                aria-hidden="true" ></span>
            </a></b>
        </td>

        {% for header in headers %}
            <td  style="color:#167249"
            {% if forloop.counter0 > 1  %}
                align="center"
                width="14%"
            {% else %}
                width="10%"
            {% endif %}
            {% if header == "Overall Progress" %}
                colspan="3" >
                <b>
                    {% if all_results %}
                    <a href="{% url 'hkstat-progress-block'%}{% if form.date_from.value %}?date_from={{form.date_from.value}}{%endif%}{%if form.date_from.value and form.date_by.value %}&date_by={{form.date_by.value}}{% elif form.date_by.value %}?date_by={{form.date_by.value}}%}{% endif %}">
                        {{ header }} <span class="glyphicon glyphicon-collapse-down"></span>
                    </a>
                    {% else %}
                        {{ header }}
                    {% endif %}
                </b>
            {% elif header == "Excel Excercise" %}
                colspan="2" >
                <b style="color: #167249">{{ header }}<br></b>
            {% elif header == "Start Date" %}
                >
                <b>
                    {% if order == "date_reg" %}
                        <a href="{% url 'hkstat-progress' %}?order=-date_reg{% if form.date_from.value %}&date_from={{form.date_from.value}}{% endif %}{% if form.date_by.value %}&date_by={{form.date_by.value}}{% endif %}">
                    {% else %}
                        <a href="{% url 'hkstat-progress' %}?order=date_reg{% if form.date_from.value%}&date_from={{form.date_from.value}}{% endif %}{% if form.date_by.value %}&date_by={{form.date_by.value}}{% endif %}">
                    {% endif %}
                        {{ header}}
                    <span 
                    {% if order == "-date_reg" %}
                        class="glyphicon glyphicon-triangle-top"
                    {% else %}
                        class="glyphicon glyphicon-triangle-bottom" 
                    {% endif %}
                    aria-hidden="true"></span>
                </a></b>
            {% else %}
                >
                <b style="color: #167249">{{ header }}<br></b>
            {% endif %}
            </td>
        {% endfor %}
    </tr>
    <tr></tr>
    <tr>
        <td></td><td></td><td></td><td></td>
        <td align="right"><span class="glyphicon glyphicon-education" aria-hidden="true" style="color: #167249"></span> &nbsp;</td>
        <td align="center"><img src="{% static "/media/game.png" %}"  alt="Game"></td>
        <td align="left"><span class="glyphicon glyphicon-time" aria-hidden="true" style="color: #167249"></span> &nbsp;</td>
        <td></td>
        <td align="right"><img src="{% static "/media/game.png" %}"  alt="Game">&nbsp;&nbsp;</td>
        <td align="left">&nbsp;<span class="glyphicon glyphicon-time" aria-hidden="true" style="color: #167249"></span> </td>
        

    </tr>
    {% for learner, result in all_results %}
    <tr>
        <td align="left">
            {{learner.surname}}
        </td>
        <td> {{learner.name}} </td>
        <td>{{ learner.email }}</td>
        <td align="center">
            {{learner.date_reg|date:"m/d/Y"}}
        </td>
        <td align="right" style="color: #167249" title="Academy">
            {{result.academy|floatformat:2}}%
        </td>
        <td align="center" style="color: #eb6f1f" title="Game">
            {{result.game|floatformat:2}}%
        </td>
        <td align="left" style="color: #443c36" title="Time">
            {{result.time}}
        </td>
        <td>
            <div class="progress">
                    <div 
                    {% if result.all_percent >= 50 %}
                        class="progress-bar progress-bar-success" 
                    {% else %}
                        class="progress-bar progress-bar-warning"
                    {% endif %}
                    role="progressbar" 
                        aria-valuenow={{result.all_percent}}
                        aria-valuemin="0"
                        aria-valuemax="100" 
                        style="min-width: 3em; width: {{result.all_percent|floatformat:2}}%">
                        {{result.all_percent|floatformat:2}}%
                    </div>
                </div>
        </td>
        <td align="right" style="color: #eb6f1f" title="Percent">
            {{result.excercise_percent|floatformat:2}}%
        </td>
        <td align="left" style="color: #443c36" title="Time">
            {{result.excercise_time}}
        </td>
    </tr>
    {% endfor %}
</table>
<br>
<div class="row" >
    <div class="col-md-offset-5 col-md-1">
        <a href="{% url 'HotKeyStat-index' %}" class="btn btn-warning btn-block">Home</a>
    </div>
    <div class="col-md-1 ">
        <a href="{% url 'HotKeyStat-index' %}" class="btn btn-warning btn-block"> Back </a>
    </div>
 </div>
{% endblock %}